language: node_js
node_js:
  - "stable"

before_script:
  - "export DISPLAY=:99.0"
  - "npm i -g jasmine"
  - "npm install -g grunt-cli"
  - "grunt"

script:
  - 'npm test'
  - 'jasmine spec/integrationtest.js'
