sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "stable"

before_script:
  - npm i -g jasmine
  - npm install -g grunt-cli
  - grunt serve

script:
  - npm test
  - jasmine spec/integrationtest.js
